spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    pyApp:
      repoURL: https://github.com/rstrazza/py-app.git
      targetRevision: main
      path: k8s/prod
      destination:
        namespace: blue
    bbEksUtils:
      repoURL: https://github.com/rstrazza/bb-eks-utils.git
      targetRevision: main
      path: k8s/prod
      destination:
        namespace: green
