apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.spec.apps.prometheus.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    chart: prometheus
    helm:
      values: |
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - prometheus-dev.eks.strazza.dev
          paths:
            - /
    repoURL: {{ .Values.spec.apps.prometheus.repoURL }}
    targetRevision: {{ .Values.spec.apps.prometheus.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
