apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: py-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: {{ .Values.spec.apps.pyApp.destination.namespace }}
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.apps.pyApp.repoURL }}
    targetRevision: {{ .Values.spec.apps.pyApp.targetRevision }}
    path: {{ .Values.spec.apps.pyApp.path }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
