spec:
  destination:
    server: https://kubernetes.default.svc
  apps:
    pyApp:
      repoURL: https://github.com/rstrazza/py-app.git
      targetRevision: main
      path: k8s/dev
      destination:
        namespace: blue
    # prometheus:
    #   repoURL: https://prometheus-community.github.io/helm-charts
    #   targetRevision: 15.10.4
    #   destination:
    #     namespace: prometheus
